Implement reading and writing for non-byte arrays
zaksabeast/no_std_io pull request #3
Opened 2023-05-19 18:09 UTC by SteveCookTU

Note: This PR will start as a draft to serve  discussion and change of the base idea that is implemented. Once things have been cleaned up and implementation is fully discussed, it will be finalized for full review.

2023-05-24 00:55 UTC, zaksabeast requested changes
Small change, but otherwise looks good.

2023-05-24 00:55 UTC, zaksabeast commented on src/stream/writer.rs
> +        let size = value[0].get_size() * SIZE;
Not all items are guaranteed to be the same size.

For example, a nex list can be a variable size.  If the first is 4 bytes and the second is 8, we'll get an incorrect count each time.

2023-05-24 02:33 UTC, SteveCookTU commented on src/stream/writer.rs
> +        let size = value[0].get_size() * SIZE;
Good catch, I thought about this for the loop after but not for checking the size

2023-05-29 20:07 UTC, zaksabeast approved these changes

2023-05-29 20:07 UTC, merged